INSERT INTO CATEGORY(description) VALUES('American')
INSERT INTO CATEGORY(description) VALUES('Mexican')
INSERT INTO CATEGORY(description) VALUES('Italian')
INSERT INTO CATEGORY(description) VALUES('African')
INSERT INTO UNIT_OF_MEASURE(uom) VALUES('Tablespoon')
INSERT INTO UNIT_OF_MEASURE(uom) VALUES('Teaspoon')
INSERT INTO UNIT_OF_MEASURE(uom) VALUES('Cup')
INSERT INTO UNIT_OF_MEASURE(uom) VALUES('Pinch')
INSERT INTO UNIT_OF_MEASURE(uom) VALUES('Ounce')
INSERT INTO UNIT_OF_MEASURE(uom) VALUES('Dash')
INSERT INTO UNIT_OF_MEASURE(uom) VALUES('Each')
INSERT INTO UNIT_OF_MEASURE(uom) VALUES('Pint')


